{
 "title": "BGP statistics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n  bucket: \"telemetry\",\n  measurement: \"/interfaces/\",\n  tag: \"device\"\n)"
   },
   {
    "name": "BGP_neighbors",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n  bucket: \"telemetry\",\n  measurement: \"/network-instances/\",\n  tag: \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\"\n)"
   },
   { "name": "BGP_family", "query": "IPV4_UNICAST,IPV6_UNICAST" },
   { "name": "DB", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Essentials", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Our AS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/global/state/as\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Established peering (v4, v6, internal, external, last 5min))",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -1m,  stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state\" and r._value == \"ESTABLISHED\")\n  |> last()\n  |> count()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Non-established peering (last 5min)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"telemetry\")\n  |> range(start: -5m,  stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state\" and r._value != \"ESTABLISHED\")\n  |> last()\n  |> count()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total prefixes received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/global/state/total-prefixes\")\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Prefixes received & installed per neighbor",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  received = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received\" or r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/installed\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name\"] =~ /${BGP_family:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Percentage of installed vs received prefixes per neighbor",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  received = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received\" or r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/installed\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name\"] =~ /${BGP_family:regex}/)\n  |> aggregateWindow(every: 30d, fn: last, createEmpty: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _measurement: r._measurement,\n    _field: r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\"],\n    _value: if float(v: r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received\"]) == 0.0 then 0.0\n        else float(v: r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/installed\"]) / float(v: r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received\"]) * 100.0\n  }))\n  |> sort(columns: [\"_value\"], desc: true)\n  |> yield(name: \"last\")\n\n\n"
    }
   ]
  },
  {
   "title": "Prefixes received & installed per neighbor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "  received = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/accepted\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name\"] =~ /${BGP_family:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    },
    {
     "query": "  received = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/installed\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name\"] =~ /${BGP_family:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  { "title": "BGP status matrix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "BGP status",
   "type": "status-history",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state\")\n  |> group(columns: [\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\"])\n  |> keep(columns: [\"_time\", \"_value\", \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Prefixes state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "BGP total prefixes received",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/global/state/total-prefixes\")\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> set(key: \"_field\", value: \"Total received prefixes\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BGP prefixes installed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/installed\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\"] =~ /${BGP_neighbors:regex}/)\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name\"] =~ /${BGP_family:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BGP prefixes accepted",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/accepted\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\"] =~ /${BGP_neighbors:regex}/)\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name\"] =~ /${BGP_family:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BGP prefixes sent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/sent\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\"] =~ /${BGP_neighbors:regex}/)\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name\"] =~ /${BGP_family:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BGP prefixes received",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/network-instances/\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received\")\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/@neighbor-address\"] =~ /${BGP_neighbors:regex}/)\n  |> filter(fn: (r) => r[\"/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/@afi-safi-name\"] =~ /${BGP_family:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}