{
 "title": "Interface statistics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n  bucket: \"telemetry\",\n  measurement: \"/interfaces/\",\n  tag: \"device\"\n)"
   },
   {
    "name": "if_name",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.tagValues(\n    bucket: \"telemetry\",\n    tag: \"/interfaces/interface/@name\",\n    predicate: (r) => r.device == \"${host_regex}\",\n    start: -1d\n)\n"
   },
   {
    "name": "queue",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.tagValues(\n    bucket: \"telemetry\",\n    tag: \"/interfaces/interface/state/counters/out-queue/@queue-number\",\n    predicate: (r) => r.device == \"${host_regex}\",\n    start: -1d\n)\n"
   },
   { "name": "DB", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Interface statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic statistics (pps)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "out_dir = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-pkts\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> set(key: \"_field\", value: \"OUT\")\n  \nin_dir = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/in-pkts\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> set(key: \"_field\", value: \"IN\")\n\n  union(tables: [out_dir, in_dir])\n    |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Traffic statistics (Bps)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "out_dir = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-octets\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> map(fn: (r) => ({\n    r with \n    _value: r._value * 8.0\n  })\n  ) \n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> set(key: \"_field\", value: \"OUT\")\n\n  in_dir = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/in-octets\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> map(fn: (r) => ({\n    r with \n    _value: r._value * 8.0\n  })\n  ) \n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> set(key: \"_field\", value: \"IN\")\n\nunion(tables: [out_dir, in_dir])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Traffic statistics errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/ethernet/state/counters/in-crc-errors\" or r[\"_field\"] == \"/interfaces/interface/ethernet/state/counters/in-block-errors\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Traffic statistics - Unicast/Multicast/Broadcast packets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "unicast = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-unicast-pkts\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nmulticast = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-multicast-pkts\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nbroadcast = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-broadcast-pkts\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n  union(tables: [unicast, multicast, broadcast])\n    |> yield(name: \"last\")\n"
    },
    {
     "query": "unicast = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/in-unicast-pkts\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nmulticast = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/in-multicast-pkts\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nbroadcast = from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/in-broadcast-pkts\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n\n  union(tables: [unicast, multicast, broadcast])\n    |> yield(name: \"last\")\n"
    }
   ]
  },
  { "title": "Interface queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Interface queue stats (pps)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-queue/pkts\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/state/counters/out-queue/@queue-number\"] =~ /${queue:regex}/)\n  |> derivative(unit: 1s, nonNegative: true)\n    |> map(fn: (r) => ({\n    r with \n    _value: r._value * 8.0\n  })\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Interface queue stats (Bps)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-queue/bytes\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/state/counters/out-queue/@queue-number\"] =~ /${queue:regex}/)\n  |> derivative(unit: 1s, nonNegative: true)\n    |> map(fn: (r) => ({\n    r with \n    _value: r._value * 8.0,\n  })\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Interface buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Interface Buffer occupancy (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-queue/avg-buffer-occupancy\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/state/counters/out-queue/@queue-number\"] =~ /${queue:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> yield(name: \"last\")\n  |> group(columns: [\"device\", \"/interfaces/interface/@name\", \"/interfaces/interface/state/counters/out-queue/@queue-number\"])"
    }
   ]
  },
  {
   "title": "Interface Buffer occupancy (current)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-queue/cur-buffer-occupancy\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/state/counters/out-queue/@queue-number\"] =~ /${queue:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> yield(name: \"last\")\n  |> group(columns: [\"device\", \"/interfaces/interface/@name\", \"/interfaces/interface/state/counters/out-queue/@queue-number\"])"
    }
   ]
  },
  {
   "title": "Interface Buffer occupancy (peak)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"/interfaces/\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/@name\"] =~ /${if_name:regex}/)\n  |> filter(fn: (r) => r[\"device\"] == \"${host_regex}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"/interfaces/interface/state/counters/out-queue/peak-buffer-occupancy\")\n  |> filter(fn: (r) => r[\"/interfaces/interface/state/counters/out-queue/@queue-number\"] =~ /${queue:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n  |> yield(name: \"last\")\n  |> group(columns: [\"device\", \"/interfaces/interface/@name\", \"/interfaces/interface/state/counters/out-queue/@queue-number\"])"
    }
   ]
  }
 ]
}